### Movies Index
GET http://localhost:3000/movies.json

### Movies Create
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "name": "Kung-Fu Hustle",
  "image_url": "https://upload.wikimedia.org/wikipedia/en/0/00/KungFuHustleHKposter.jpg",
  "description": "The film tells the story of a murderous neighbourhood gang, a poor village with unlikely heroes, and an aspiring gangster's fierce journey to find his true self",
  "genre": "Gangster Comedy"
}


### Favorites Index
GET http://localhost:3000/favorites.json 
### Favorites Create
POST http://localhost:3000/favorites.json 
Content-Type: application/json 

{
  "user_id": 3,
  "movie_id": 1
}

### Favorites Destroy 
DELETE http://localhost:3000/favorites/1.json 



### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json 

{
  "name": "Jules",
  "email": "jules1@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json 
Content-Type: application/json 

{
  "email": "jada@test.com",
  "password": "password"
}

### Search All Movies

GET http://localhost:3000/movies/search.json?t=the matrix



### WatchMode
GET https://api.watchmode.com/v1/sources/?apiKey=lhn1ehZ9TblSHpRqTfjr5gJhpvRuaIHXRue94nsF

